let employees=[{"id":1,"name":"Ethelda","gender":"Female"},
    {"id":2,"name":"Udale","gender":"Male"},
    {"id":3,"name":"Addi","gender":"Female"},
    {"id":4,"name":"Latisha","gender":"Female"},
    {"id":5,"name":"Dasi","gender":"Female"},
    {"id":6,"name":"Robin","gender":"Male"},
    {"id":7,"name":"Karen","gender":"Female"},
    {"id":8,"name":"Berrie","gender":"Female"},
    {"id":9,"name":"Kalle","gender":"Male"},
    {"id":10,"name":"Arvie","gender":"Male"},
    {"id":11,"name":"Smith","gender":"Male"},
    {"id":12,"name":"Kelila","gender":"Female"},
    {"id":13,"name":"Cornie","gender":"Male"},
    {"id":14,"name":"Bobby","gender":"Male"},
    {"id":15,"name":"Noellyn","gender":"Female"},
    {"id":16,"name":"Duke","gender":"Male"},
    {"id":17,"name":"Salomo","gender":"Male"},
    {"id":18,"name":"Daren","gender":"Male"},
    {"id":19,"name":"Petunia","gender":"Agender"},
    {"id":20,"name":"Natale","gender":"Non-binary"},
    {"id":21,"name":"Garik","gender":"Male"},
    {"id":22,"name":"Althea","gender":"Polygender"},
    {"id":23,"name":"Loella","gender":"Female"},
    {"id":24,"name":"Yorke","gender":"Male"},
    {"id":25,"name":"Enos","gender":"Male"},
    {"id":26,"name":"Pat","gender":"Male"},
    {"id":27,"name":"Dal","gender":"Male"},
    {"id":28,"name":"Ardella","gender":"Female"},
    {"id":29,"name":"Sid","gender":"Male"},
    {"id":30,"name":"Sergio","gender":"Male"},
    {"id":31,"name":"Wright","gender":"Male"},
    {"id":32,"name":"Shermy","gender":"Male"},
    {"id":33,"name":"Phaidra","gender":"Female"},
    {"id":34,"name":"Winifred","gender":"Female"},
    {"id":35,"name":"Korey","gender":"Male"},
    {"id":36,"name":"Kennie","gender":"Male"},
    {"id":37,"name":"Eddie","gender":"Male"},
    {"id":38,"name":"Katerina","gender":"Female"},
    {"id":39,"name":"Foster","gender":"Male"},
    {"id":40,"name":"Ferdinand","gender":"Male"},
    {"id":41,"name":"Barbara-anne","gender":"Female"},
    {"id":42,"name":"Yardley","gender":"Male"},
    {"id":43,"name":"Cookie","gender":"Female"},
    {"id":44,"name":"Dominga","gender":"Genderqueer"},
    {"id":45,"name":"Lorilyn","gender":"Female"},
    {"id":46,"name":"Inge","gender":"Female"},
    {"id":47,"name":"Yurik","gender":"Male"},
    {"id":48,"name":"Dud","gender":"Male"},
    {"id":49,"name":"Mel","gender":"Male"},
    {"id":50,"name":"Lissa","gender":"Female"}]


for(emp of employees){
    if(emp.gender  ==="Female"){
        console.log("Emp Id",emp.id,"and Name",emp.name,"Gender:",emp.gender)
    }
}